Add Texpacker
hoverguys/rehover pull request #18
Opened 2017-12-20 13:10 UTC by silverweed

(See #12)
Texpacker now works hopefully well. I tried sticking to the rest of the tools' style as much as possible, so it should be pretty familiar to review.

### Usage
```
$ ./texpacker -h
Usage: ./texpacker [flags] <file1> [<file2> ...]
  -noheader
    	Don't write header, output raw PNG
  -o string
    	Output file (- for STDOUT) (default "-")
  -strip string
    	Prefix to strip from file paths for hashing (default <cwd>)

Supported input formats:
    JPEG
    GIF
    PNG
```
Basically it takes input textures as positional arguments and spits out a binary file with the format `[header | PNG image]`. It can be told to output just the PNG for debugging purposes.
The `-strip` flag is used to make the tool usable from any directory: the hashed paths will be relative to the path given to `-strip`.

The packing algorithm is currently maxrects and uses  `"github.com/adinfinit/texpack/maxrect"` which is MIT-licensed.

Forgot anything?

2017-12-20 15:06 UTC, Hamcha requested changes
This is still using a single file for output while it should do two (packed PNG + metadata). My original doc referred to "Header" meaning "C header file", not header of the actual texture.

2017-12-20 15:06 UTC, Hamcha commented on tools/build.sh
> +go build -o bin/texpacker ./texpacker
Please add the "go get" command on top of both build files, just like tools-extra/build.*

2017-12-20 15:22 UTC, zeroZshadow requested changes

2017-12-20 15:22 UTC, zeroZshadow commented on tools/texpacker/format.go
> +	Start, Size Point
Size isn't a point, so either rename `Point` to be less specialized (Vector2?)
Or change what Size is?

2017-12-20 15:22 UTC, zeroZshadow commented on tools/texpacker/main.go
> +	stripPfx := flag.String("strip", cwd, "Prefix to strip from file paths for hashing")
Why not call this `-prefix`? The current name sounds like its a toggle flag

2017-12-20 15:22 UTC, zeroZshadow commented on tools/texpacker/main.go
> +	maxBounds := image.Point{1 << 16, 1 << 16} // TODO
Forgot a TODO here, flag?

2017-12-20 15:22 UTC, zeroZshadow commented on tools/texpacker/format.go
> +	if err != nil {
Why doesnt this use checkErr ?

2017-12-20 15:22 UTC, zeroZshadow commented on tools/texpacker/main.go
> +	if err := packer.Save(); err != nil {
Why doesn this use checkErr ?

2017-12-20 15:22 UTC, zeroZshadow commented on tools/texpacker/packer.go
> +func writeImageAt(dst *image.RGBA, src image.Image, x, y int) error {
This could instead use `image.SubImage` and the `image/draw` functions?

2017-12-20 15:22 UTC, zeroZshadow commented on tools/texpacker/packer.go
> +				shrunk = true
This will still cause it to try shrinkY, is that ok?

2017-12-21 10:37 UTC, silverweed commented on tools/texpacker/packer.go
> +				shrunk = true
That's probably a typo in the function I copy-pasted, it should be `shrinkY = false` in the `shrinkY` branch.

2017-12-21 10:48 UTC, silverweed commented
Ok, shouls have fixed all issues. Now the tool outputs 2 files: `<outfile>` and `<outfile>.atlas`, the latter containing the metadata in the exact same format as described in OP.
I've removed the `-noheader` flag and the possibility to output to stdout, as these would yield ill-defined image/metadata pairs.

2017-12-21 13:17 UTC, zeroZshadow commented on tools/texpacker/main.go
> +	maxW := flag.Int("maxwidth", 1<<16, "Max width of output texture in pixels")
Up for discussion, do we wanna support non-square atlasses? if not, only needs 1 flag ;)

2017-12-21 13:19 UTC, zeroZshadow commented on tools/texpacker/packer.go
> +	return
If this returns an error, `TexPacker.Save` will not close the `imageOut`

2017-12-21 15:34 UTC, Hamcha commented on tools/texpacker/main.go
> +	maxW := flag.Int("maxwidth", 1<<16, "Max width of output texture in pixels")
No reason to, I think.

2017-12-21 15:36 UTC, Hamcha approved these changes

2017-12-22 15:27 UTC, silverweed commented
Latest commit should have fixed both issues.

2017-12-22 17:14 UTC, zeroZshadow approved these changes

2017-12-22 18:05 UTC, merged